openapi: 3.0.0

info:
    title: Get VPN API IP Address Information
    description: Get detailed information from VPN API about an IP Address.
    #Examples
    #Can you summarize the VPN API information for the IP 185.220.101.140?
    #Can you summarize the IP address information from VPN API for the IP 75.156.61.64?
    version: "v1"

servers:
    - url: https://vpnapi.io

paths:
    /api/{ip}:
        get:
            operationId: getVPNAPIIP
            summary: Get VPN API IP Information for a particular IP address.
            parameters:
                - in: path
                  name: ip
                  schema:
                      type: string
                  required: true
                  description: The ip address to lookup              
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/getVPNAPIIPResponse"

        responses:
          "201":
            description: The incident object created.
            content:
              application/json:
                schema:
                  type: object